#!/bin/bash
BIN_DIR="/usr/sbin"

if [[ $USER != "root" ]]; then
    echo "please use sudo instruct ...";
    exit 1;
fi

echo -e "\033[36m 开始启动! \033[0m";
echo -e "\033[33mnginx stop ...\033[0m"

#关闭nginx服务
$BIN_DIR/service nginx stop
echo -e "\033[32mnginx down ...\033[0m"

#关闭mysql服务
echo -e "\033[33mmysql stop ...\033[0m"
$BIN_DIR/service mysql stop
echo -e "\033[32mmysql down ...\033[0m"

#关闭redis-server服务
echo -e "\033[33mredis-server stop ...\033[0m"
$BIN_DIR/service redis-server stop
echo -e "\033[32mredis-server down ...\033[0m"

#关闭php7.2-fpm服务
echo -e "\033[33mphp7.2-fpm stop ...\033[0m"
$BIN_DIR/service php7.2-fpm stop
echo -e "\033[32mphp7.2-fpm down ...\033[0m"

#关闭supervisor服务
echo -e "\033[33msupervisor stop ...\033[0m"
$BIN_DIR/service supervisor stop
echo -e "\033[32msupervisor down ...\033[0m"
